FROM python:3.7.3
MAINTAINER Mark McConnell <mjmccconnell.dev@gmail.com>

RUN apt update && apt install -y

COPY Pipfile /opt/Pipfile
COPY Pipfile.lock /opt/Pipfile.lock

WORKDIR /opt
RUN pip3 install pipenv
RUN pipenv install --system

COPY app /opt/app
WORKDIR /opt/app
