FROM python:3.7.3
MAINTAINER Mark McConnell <mjmccconnell.dev@gmail.com>

RUN apt update && apt install -y

COPY app/Pipfile /opt/Pipfile
COPY app/Pipfile.lock /opt/Pipfile.lock

WORKDIR /opt

RUN pip3 install pipenv
RUN pipenv install --system --dev --pre

COPY app /opt
